import findspark
findspark.init("/opt/spark")

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-1.17.0-openjdk-amd64"

from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.sql.window import Window
import json
import os
import sys


class SalesDashboard:
    def __init__(self):
        try:
            self.spark = SparkSession.builder \
                .appName("SalesDashboard") \
                .config("spark.sql.adaptive.enabled", "true") \
                .getOrCreate()
            
            # Set log level to ERROR to reduce console clutter
            self.spark.sparkContext.setLogLevel("ERROR")
            
            print("Sales Dashboard initialized successfully")
            print(f"Spark Version: {self.spark.version}")
            print()
            
        except Exception as e:
            print(f"Error initializing Spark session: {str(e)}")
            sys.exit(1)
    
    def load_data(self, path):
        try:
            if not os.path.exists(path):
                raise FileNotFoundError(f"Data file not found: {path}")
            
            df = self.spark.read.parquet(path)
            print(f"Loaded data from {path}")
            print(f"Total records: {df.count():,}")
            return df
            
        except Exception as e:
            print(f"Error loading data: {str(e)}")
            raise
    
    def calculate_kpis(self, df):
        try:
            # add calculated column for total transaction amount
            df = df.withColumn("total_amount", F.col("price") * F.col("quantity"))
            
            # calculate total revenue by summing all transaction amounts
            total_revenue = df.agg(F.sum("total_amount")).collect()[0][0]
            
            # count total number of transactions
            total_transactions = df.count()
            
            # count unique customers to measure customer base size
            unique_customers = df.select("customer_id").distinct().count()
            
            # calculate average value per transaction
            avg_order_value = total_revenue / total_transactions if total_transactions > 0 else 0
            
            return {
                "total_revenue": float(total_revenue) if total_revenue else 0.0,
                "total_transactions": int(total_transactions),
                "unique_customers": int(unique_customers),
                "avg_order_value": float(avg_order_value)
            }
            
        except Exception as e:
            print(f"Error calculating KPIs: {str(e)}")
            raise
    
    def top_performers(self, df):
        try:
            # Group by product and calculate metrics
            top_products = df.groupBy("product") \
                .agg(
                    # Total revenue generated by this product
                    F.sum("total_amount").alias("revenue"),
                    # Total units sold (sum of quantities)
                    F.sum("quantity").alias("units_sold")
                ) \
                .orderBy(F.desc("revenue")) \
                .limit(5)
            
            return top_products
            
        except Exception as e:
            print(f"Error analyzing top performers: {str(e)}")
            raise
    
    def trend_analysis(self, df):
        try:
            # Aggregate sales by month
            monthly_trends = df.groupBy("month") \
                .agg(
                    # Total revenue per month
                    F.sum("total_amount").alias("revenue"),
                    # Transaction count per month
                    F.count("transaction_id").alias("transactions")
                ) \
                .orderBy("month")
            
            # define window for calculating previous month values
            # window is ordered by month to enable lag function
            window = Window.orderBy("month")
            
            # Add previous month's revenue and calculate growth rate
            trends_with_growth = monthly_trends.withColumn(
                "prev_month_revenue",
                F.lag("revenue").over(window)
            ).withColumn(
                "growth_rate",
                # calculate percentage change from previous month
                # formula: ((current - previous) / previous) * 100
                ((F.col("revenue") - F.col("prev_month_revenue")) /
                 F.col("prev_month_revenue") * 100)
            )
            
            return trends_with_growth
            
        except Exception as e:
            print(f"Error in trend analysis: {str(e)}")
            raise
    
    def segment_customers(self, df):
        try:
            # aggregate customer behavior metrics
            customer_segments = df.groupBy("customer_id") \
                .agg(
                    # lifetime value: total amount spent
                    F.sum("total_amount").alias("total_spend"),
                    # purchase frequency: number of transactions
                    F.count("transaction_id").alias("num_purchases"),
                    # average transaction size
                    F.avg("total_amount").alias("avg_purchase_value")
                ) \
                .withColumn("segment",
                    # categorize customers into value tiers
                    F.when(F.col("total_spend") > 10000, "High Value")
                    .when(F.col("total_spend") > 5000, "Medium Value")
                    .otherwise("Low Value")
                )
            
            return customer_segments
            
        except Exception as e:
            print(f"Error in customer segmentation: {str(e)}")
            raise
    
    def save_results(self, kpis, top_products, trends, customer_segments):
        try:
            print("Saving analysis results...")
            print("-" * 60)
            
            # Save KPIs as JSON for easy parsing
            with open("kpis.json", "w") as f:
                json.dump(kpis, f, indent=4)
            print("Saved kpis.json")
            
            # Save DataFrames as CSV files            
            top_products.coalesce(1).write \
                .mode("overwrite") \
                .option("header", "true") \
                .csv("top_products_output")
            print("Saved top_products.csv (in top_products_output folder)")
            
            trends.coalesce(1).write \
                .mode("overwrite") \
                .option("header", "true") \
                .csv("monthly_sales_output")
            print("Saved monthly_sales.csv (in monthly_sales_output folder)")
            
            customer_segments.coalesce(1).write \
                .mode("overwrite") \
                .option("header", "true") \
                .csv("customer_segments_output")
            print("Saved customer_segments.csv (in customer_segments_output folder)")
            
        except Exception as e:
            print(f"Error saving results: {str(e)}")
            raise
    
    def run(self):
        try:
            print("=" * 60)
            print("SALES DASHBOARD - EXECUTION STARTED")
            print("=" * 60)
            print()
            
            # Load transaction data from Parquet
            df = self.load_data("transactions.parquet")
            print()
            
            # total_amount: revenue per transaction (price × quantity)
            # month: extracted from date for temporal analysis
            print("Preparing data for analysis...")
            df = df.withColumn("total_amount", F.col("price") * F.col("quantity")) \
                   .withColumn("month", F.month(F.col("date")))
            
            # Cache the DataFrame since we'll use it multiple times
            df.cache()
            print("Data prepared and cached in memory")
            
            # Execute all analyses
            print("Running analytics...")
            print("-" * 60)
            
            print("1. Calculating KPIs...")
            kpis = self.calculate_kpis(df)
            print(f"   Total Revenue: ${kpis['total_revenue']:,.2f}")
            print(f"   Total Transactions: {kpis['total_transactions']:,}")
            print(f"   Unique Customers: {kpis['unique_customers']:,}")
            print(f"   Average Order Value: ${kpis['avg_order_value']:,.2f}")
            
            print("2. Identifying top performing products...")
            top_products = self.top_performers(df)
            print(f"   Analyzed {top_products.count()} product categories")
            
            print("3. Analyzing sales trends...")
            trends = self.trend_analysis(df)
            print(f"   Generated trends for {trends.count()} months")
            
            print("4. Segmenting customers...")
            customer_segments = self.segment_customers(df)
            print(f"   Segmented {customer_segments.count()} customers")
            
            # save all results to files
            self.save_results(kpis, top_products, trends, customer_segments)
            
            # display completion summary
            print("=" * 60)
            print("SALES DASHBOARD - EXECUTION COMPLETED")
            print("=" * 60)
            print("All analysis results have been saved successfully!")
            print("Deliverable files generated:")
            print("  1. kpis.json - Key performance indicators")
            print("  2. top_products_output/ - Top performing products")
            print("  3. monthly_sales_output/ - Monthly sales trends")
            print("  4. customer_segments_output/ - Customer segmentation")
            print("Spark UI available at: http://localhost:4040")
            
        except FileNotFoundError as e:
            print("=" * 60)
            print("ERROR: Required Data Not Found")
            print("=" * 60)
            print(f"\n{str(e)}")
            print("\nPlease run dataframe_operations.py (Part 2) first to generate")
            print("the transactions.parquet file needed for this dashboard.")
            
        except Exception as e:
            print("=" * 60)
            print("ERROR: Dashboard Execution Failed")
            print("=" * 60)
            print(f"\n{str(e)}")
            print("\nPlease check the error message above and try again.")
            
        finally:
            print()
            try:
                input("Press Enter to stop Spark session...")
            except KeyboardInterrupt:
                print("\nReceived interrupt signal...")
            
            try:
                self.spark.stop()
                print("Spark session stopped successfully")
            except:
                pass


if __name__ == "__main__":
    print("*" * 60)
    print("*  LAB 3 PART 5: SALES DASHBOARD")
    print("*  Apache Spark Business Intelligence Application")
    print("*" * 60)
    
    # Create and run the dashboard
    dashboard = SalesDashboard()
    dashboard.run()